# Generated by Django 2.0.7 on 2018-07-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180718_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manufacturing_date',
            new_name='order_date',
        ),
    ]
