# Generated by Django 2.0.7 on 2018-07-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180718_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='date manufactured'),
        ),
    ]
