# Generated by Django 2.0.7 on 2018-07-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20180719_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Ordered on'),
        ),
    ]
