# Generated by Django 2.0.7 on 2018-07-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180719_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pname',
            field=models.CharField(max_length=100, verbose_name='Product Name'),
        ),
    ]
